### ISSUE TITLE
bug: Running `aim!help` in DMs causes the bot to error

### ISSUE THREAD

**Issue by CircuitSacul** [XerexDiscordBot/AIMod#1]
**Describe The Bug**
Running `aim!help` in a guild sends you a dm, and then 60 seconds later it deletes the invocation command I sent. However, since the bot is unable to delete messages in DMs, the bot causes an error. (at least this is my best guess as to why)

**Steps To Reproduce**
Run `aim!help` in DMs, the error should occur in 60 seconds

**Expected Behavior**
The bot still behaves normally on the user-end, but it logs an error

**Actual Result**
It logs an error

**Additional Information**
Pretty sure the problem is here https://github.com/XerexDiscordBot/AIMod/blob/119742cc6ecd004344c5d160ce8aff7281648f43/functions/commandfunctions/help/commandinfo.js#L18

**Comment by CamTheHelpDesk** [comment]
This also appears to happen when the bot attempts to delete a message without permissions.

**Comment by CircuitSacul** [comment]
Adding the check on that line will also fix that though, so you can solve both problems.

However I would recommend not even trying to delete the message if it's dms, because each API request counts

**Comment by CamTheHelpDesk** [comment]
Yeah, agreed. It would probably be best to just check perms before instead of catching. I'll take a look.
