### ISSUE TITLE
Privacy Leak

### ISSUE THREAD

**Issue by CircuitSacul** [XerexDiscordBot/AIMod#5]
I noticed that the bot logs reported messages to the console. This feels like a privacy leak to me, and would really appreciate it if you could remove this. Maybe just log that a report was made plus the toxicity level, but not the message content, author, reporter, or guild.

**Comment by CamTheHelpDesk** [comment]
Actually, the bot **ONLY** logs the message, message reporter, and the score it received- nothing else. (PROOF: https://cam.is-ne.at/CXAh9p.png)

While this may change in the future, particularly if a modlog channel feature is created, all of this information is true for the time being.

These are recorded for debugging purposes, which are explained in the privacy policy. `aim!privacy`

You can double check this in the code, if you'd like.
